version: '3.9'

services:
  web:
    build:
      context: .
    command: sh /app/entrypoint.sh
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - back_static:/app/static
      - back_media:/app/media
    restart: always

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    restart: always

  celery_worker:
    build:
      context: .
    command: celery -A shop_api worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  celery_beat:
    build:
      context: .
    command: celery -A shop_api beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  celery_flower:
    build:
      context: .
    command: celery -A shop_api flower --port=5555
    ports:
      - "5556:5555"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - back_static:/app/static
      - back_media:/app/media
    depends_on:
      - web
    restart: always

volumes:
  db-data:
  redis-data:
  back_static:
  back_media:
