# Generated by Django 5.2.4 on 2025-09-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tittle',
            new_name='title',
        ),
    ]
